name: build
on: workflow_dispatch
jobs:
  main:
    runs-on: ghcr.io/zehome/sintls-build
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - run: docker pull ghcr.io/zehome/sintls-build:latest

      - uses: actions/checkout@v2

      - run: make OUTDIR=tmp release

      - run: gbp buildpackage
        env:
          PYTHON_MATCH: ${{ matrix.PYTHON_MATCH }}

      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: sintls-*
          path: tmp/

      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: *.deb *.dsc
          path: ../