name: build
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    container: ghcr.io/zehome/sintls-build
    steps:
      - uses: actions/checkout@v2
      - run: make OUTDIR=tmp release
      - run: gbp buildpackage
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: |
            tmp/sintls-*
            ../*.deb
            ../*.dsc
            ../*.tar*
